name: "rabbitmq"

services:

  rabbitmq:
    # https://hub.docker.com/_/rabbitmq
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
        - 5673:5672
        - 15673:15672
    volumes:
        - ./docker_volumes/rabbitmq/data/:/var/lib/rabbitmq/
        - ./docker_volumes/rabbitmq/log/:/var/log/rabbitmq