name: "azurite"

services:

  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite:3.34.0
    expose:
      - 10000
      - 10001
      - 10002
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - ./docker_volumes/azurite:/data mcr.microsoft.com/azure-storage/azurite
