name: "postgres"

services:

  postgres:
    container_name: postgres
    image: postgres:17.0
    ports:
      - 5432:5432
    volumes:
      - ./config/postgres:/docker-entrypoint-initdb.d      
      - ./docker_volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=admin
      - POSTGRES_DB=demo_db
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
